# Generated by Django 5.2.6 on 2025-09-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntaQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='preguntaQuiz.preguntaquiz')),
            ],
        ),
    ]
